version: '2'
services:
    smartcpdv1-elasticsearch:
        image: elasticsearch:6.2.4
        # volumes:
        #     - ~/volumes/jhipster/smartcpdv1/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
        command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
